spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:patpat-dev}
springdoc:
  swagger-ui:
    enabled: true
cors:
  allowed-origins:
    - http://localhost:8080
    - http://localhost:5173
cookies:
  domain: none
bucket:
  serve: true
  public-root: ../volume/wwwroot/
  private-root: ../volume/bucket/
config:
  allow-register: true
  http: http://localhost:8080
  websocket: ws://localhost:8080
