spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:patpat-stag}
springdoc:
  swagger-ui:
    enabled: true
cors:
  allowed-origins:
    - ${HTTP_URL}
    - http://localhost:8080
    - http://localhost:5173
cookies:
  domain: none
config:
  allow-register: true
