spring:
  application:
    name: PatBoot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:patpat-dev}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  output:
    ansi:
      enabled: detect
server:
  port: 8080
springdoc:
  swagger-ui:
    operationsSorter: method
cors:
  allowed-origins:
    - http://8.130.103.241
    - http://8.130.103.241:2121
    - http://localhost:8000
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: Authorization
  allow-credentials: true
